sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2017.01
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build panda
  - panda --verbose installdeps .

before_script:
  # Install ncurses shared library on Linux/Debian using aptitude
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libncurses6 ; fi

script: prove -v -e "perl6 -Ilib" t/
